"""
This file provides AI-powered content generation and response processing.

This file also uses a configured language model to analyze Morning Brew
content, generate LinkedIn posts, and parse the structured AI response
into individual sections.
"""

import re

from google import genai

import configuration as config
import constants

def generate_linkedin_post(subject, content):
    """
    This function analyze Morning Brew content and generate a structured LinkedIn post.
    :param subject: Subject of the Morning Brew email.
    :param content:  Extracted and cleaned content from the email.
    :return: The structured response generated by the language model.
    """

    # Verify that the Gemini API key is available
    if not config.GEMINI_API_KEY:
        raise RuntimeError(constants.GEMINI_API_KEY_IS_NOT_SET)

    # Limit the input content to stay within the configured token limits
    trimmed_content = content[:12000]

    # Build the prompt with instructions for structured content generation
    prompt = f"""You are ghostwriting a LinkedIn post for a professional who reads Morning Brew
and wants to share a genuine take on today's newsletter -- not a summary of it.

First, analyze the newsletter content below. Then produce your ENTIRE response in
EXACTLY this structured format, with these exact section headers, in this exact order.
Do not add any text before SOURCE or after CONFIDENCE. Do not add extra commentary.

SOURCE
------
Morning Brew

TOPIC
-----
<one short line naming the specific topic, e.g. "US Retail Sales">

KEY_FACTS
---------
<3-5 bullet points, each one concrete number, stat, or fact pulled directly from
the content below. One fact per line, prefixed with "- ". No fact should be vague
("sales changed") -- every line must include an actual figure, date, or named detail.>

KEY_ENTITIES
------------
<2-4 bullet points naming the specific companies, indices, events, or people
mentioned in the content. One per line, prefixed with "- ".>

MAIN_INSIGHT
------------
<1-2 sentences giving YOUR actual point of view or read on what these facts mean --
not a restatement of the facts. This is the "so what," stated plainly.>

LINKEDIN_POST
-------------
<The final ready-to-publish LinkedIn post text. Follow these rules strictly:
- Do NOT open with a rhetorical question ("Are shoppers tapping out?", "Ever wonder...")
- Do NOT use throat-clearing phrases like "Let's be honest," "Here's the thing," "It makes you wonder"
- Do NOT end with generic engagement bait like "Drop your thoughts below" or "What's your take?"
- Use at most one emoji, only if it fits naturally
- Do NOT use broad interchangeable hashtags like #BusinessInsights, #MarketTrends, #Economy
- Open with the single most surprising concrete fact/number, stated plainly
- Take an actual point of view, grounded in MAIN_INSIGHT above
- Reference at least one specific number/name from KEY_FACTS/KEY_ENTITIES so it reads as informed
- Write like a real person typing a quick take: short sentences, occasional fragments, contractions
- Vary paragraph length
- If ending with a question, make it specific to the topic, not generic
- Pick 3-4 hashtags specific to the actual topic/entities, not generic business terms
- Keep it under 180 words>

CONFIDENCE
----------
<A single word: High, Medium, or Low -- how confident you are that KEY_FACTS above are
accurately drawn from the source content (not invented or misremembered), followed by
a dash and a one-sentence reason. Example: "High - all figures appear explicitly in the text.">

Newsletter subject: {subject}

Newsletter content:
{trimmed_content}
"""
    # Initialize the Gemini client using the configured API key
    client = genai.Client(api_key=config.GEMINI_API_KEY)

    # Generate the structured response from the configured AI model
    response = client.models.generate_content(model=config.GEMINI_MODEL, contents=prompt)

    # Return the generated response as cleaned text
    return response.text.strip()


def parse_structured_response(raw_text):
    """
    This function parse the structured AI response into individual labeled sections.
    :param raw_text: Raw structured response generated by the language model.
    :return: A dictionary containing the parsed sections and their corresponding
            content. Missing sections are ignored.
    """

    # Build a regular expression to identify each known section header
    pattern = r"(?m)^(" + "|".join(config.SECTIONS) + r")\s*\n-+\s*\n"

    # Split the response into headers and their corresponding content
    parts = re.split(pattern, raw_text)

    # Store each identified section and its content in a dictionary
    result = {}

    # Process the header-content pairs returned by re.split()
    for i in range(1, len(parts) - 1, 2):
        header = parts[i].strip()
        body = parts[i + 1].strip()
        result[header] = body

    # Return the parsed AI response
    return result
